#!/usr/bin/env bash
#
# Installs `ppr` as a command that runs straight from this repo.
#
# The installed binary is a small wrapper, not a copy: edit the source, run
# `ppr`, and it rebuilds itself first. Nothing to reinstall after a `git pull`.
#
# The plugins in plugins/ go on PATH alongside it, because `ppr brief --notify`
# and `ppr remind --push` resolve them by name and would otherwise be flags
# that explain why they did nothing. They are symlinks into the repo, so they
# update with a `git pull` too, and they are inert on anything but macOS.
#
#   ./scripts/install.sh               install or update
#   ./scripts/install.sh --uninstall   remove it, plugins included
#   ./scripts/install.sh --dir DIR     install somewhere specific
#   ./scripts/install.sh --no-plugins  just the ppr command
#
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NAME=ppr
UNINSTALL=0
PLUGINS=1
BIN_DIR=""

while [ $# -gt 0 ]; do
  case "$1" in
    --uninstall) UNINSTALL=1 ;;
    --no-plugins) PLUGINS=0 ;;
    --dir) BIN_DIR="${2:?--dir needs a path}"; shift ;;
    -h|--help) sed -n '2,18p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

# The reference consumers, installed by name because that is how they are
# found: `--notify` looks for `ppr-notify` on PATH and nowhere else.
PLUGIN_NAMES="ppr-notify ppr-reminders-push"

# --- pick an install directory that is already on PATH ------------------------

pick_bin_dir() {
  for dir in "${PNPM_HOME:-}" "$HOME/.local/bin" "/usr/local/bin"; do
    [ -n "$dir" ] || continue
    case ":$PATH:" in *":$dir:"*) [ -d "$dir" ] && { echo "$dir"; return; } ;; esac
  done
  echo "$HOME/.local/bin"
}

[ -n "$BIN_DIR" ] || BIN_DIR="$(pick_bin_dir)"
TARGET="$BIN_DIR/$NAME"

if [ "$UNINSTALL" = 1 ]; then
  rm -f "$TARGET"
  echo "removed $TARGET"
  for plugin in $PLUGIN_NAMES; do
    # Only ours: a symlink pointing back into this repo. Somebody else's
    # `ppr-notify` earlier on PATH is the whole point of the convention.
    if [ -L "$BIN_DIR/$plugin" ] && [ "$(readlink "$BIN_DIR/$plugin")" = "$REPO/plugins/$plugin" ]; then
      rm -f "$BIN_DIR/$plugin"
      echo "removed $BIN_DIR/$plugin"
    fi
  done
  exit 0
fi

# --- checks -------------------------------------------------------------------

command -v node >/dev/null || { echo "node is required (20.11+)" >&2; exit 1; }
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 20 ] || { echo "node 20.11+ required, found $(node -v)" >&2; exit 1; }
command -v pnpm >/dev/null || { echo "pnpm is required: npm i -g pnpm" >&2; exit 1; }

if [ -e "$TARGET" ] && [ ! -w "$TARGET" ]; then
  echo "cannot write $TARGET — try: sudo ./scripts/install.sh --dir $BIN_DIR" >&2
  exit 1
fi

# --- build --------------------------------------------------------------------

echo "building…"
if ! BUILD_LOG="$(cd "$REPO" && pnpm install --silent && pnpm build 2>&1)"; then
  echo "$BUILD_LOG" >&2
  echo "build failed — nothing was installed" >&2
  exit 1
fi

# --- write the wrapper --------------------------------------------------------

mkdir -p "$BIN_DIR"
cat > "$TARGET" <<WRAPPER
#!/bin/sh
# Generated by ppr/scripts/install.sh — safe to delete or regenerate.
# Runs ppr from its source repo, rebuilding first if the source has changed.
REPO="$REPO"
ENTRY="\$REPO/packages/cli/dist/index.js"

if [ ! -d "\$REPO" ]; then
  echo "ppr: source repo not found at \$REPO — it was moved or deleted." >&2
  echo "     Reinstall from wherever it lives now: ./scripts/install.sh" >&2
  exit 1
fi

if [ "\${PPR_NO_AUTOBUILD:-}" != "1" ]; then
  # A single fast scan: is any source file newer than the last build?
  if [ ! -f "\$ENTRY" ] || [ -n "\$(find "\$REPO/packages"/*/src -name '*.ts' -newer "\$ENTRY" -print -quit 2>/dev/null)" ]; then
    echo "ppr: source changed, rebuilding…" >&2
    # Buffered so a normal rebuild stays quiet, but the compiler errors are
    # shown in full when there are any — that is the moment you need them.
    if ! PPR_BUILD_LOG="\$(cd "\$REPO" && pnpm build 2>&1)"; then
      echo "\$PPR_BUILD_LOG" >&2
      # A broken build must never stop you writing a note: warn, run the last
      # good binary, and let the user fix the code when they choose to.
      echo "ppr: build failed — running the previous build" >&2
      [ -f "\$ENTRY" ] || exit 1
    fi
  fi
fi

exec node "\$ENTRY" "\$@"
WRAPPER
chmod +x "$TARGET"

# --- plugins ------------------------------------------------------------------
#
# Symlinks rather than copies, for the same reason `ppr` is a wrapper: edit the
# file, and the installed command is the edited one. An existing plugin that is
# *not* ours is left exactly where it is — replacing `ppr-notify` with your own
# is the supported way to change what `--notify` means.

if [ "$PLUGINS" = 1 ]; then
  for plugin in $PLUGIN_NAMES; do
    dest="$BIN_DIR/$plugin"
    if [ -e "$dest" ] && [ ! -L "$dest" ]; then
      echo "! $dest exists and is not ours — leaving it alone"
      continue
    fi
    ln -sf "$REPO/plugins/$plugin" "$dest"
  done
fi

# --- verify -------------------------------------------------------------------

VERSION="$("$TARGET" --version)"
echo "✓ installed ppr $VERSION -> $TARGET"

RESOLVED="$(command -v $NAME 2>/dev/null || true)"
if [ "$RESOLVED" != "$TARGET" ]; then
  if [ -z "$RESOLVED" ]; then
    echo
    echo "! $BIN_DIR is not on your PATH. Add this to your shell profile:"
    echo "    export PATH=\"$BIN_DIR:\$PATH\""
  else
    echo
    echo "! another ppr is earlier on your PATH: $RESOLVED"
  fi
  exit 0
fi

echo
echo "  ppr init            create your vault"
echo "  ppr \"first note\"    write something"
echo "  ppr --help          everything else"
if [ "$PLUGINS" = 1 ]; then
  echo "  ppr brief --notify  uses ppr-notify, installed alongside (see plugins/)"
fi
echo
echo "Edit the source and just run ppr — it rebuilds itself."
echo "For instant rebuilds while working: pnpm dev"
